config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'airports#index'
  resources :airports
#  resource :airports
  namespace :admin do
      resources :users

      root to: "users#index"
    end
  devise_for :users
end

app/models/airport.rb
class Airport < ApplicationRecord
  validates :code, presence:true, uniqueness: true
  validates :code, :length => {:maximum => 4,
                               :too_long => "Code should be 3 letters (IATA) or 4 letters (weather station)"}
  validate :check_code
  
  attr_accessor :name, :timezone, :descrip, :temp, :humidity, :wind_speed, :wind_dir, :local_time

  def load_stn
    resp = Net::HTTP.get_response(URI("https://api.weather.gov/stations/#{Airport.iata_to_stn(code)}"))
    if resp.code != "200"
      return nil
    end
    
    data = JSON.parse(resp.body)
    @status = data['status']
    if data['status'] == 404
      return nil
    end
    
    props = data['properties']
    @name = props['name']
    @timezone = TZInfo::Timezone.get(props['timeZone'])
  end

  def load_weather
    puts Airport.iata_to_stn(code)
    resp = Net::HTTP.get_response(URI("https://api.weather.gov/stations/#{Airport.iata_to_stn(code)}/observations/latest"))
    if resp.code != "200"
      return nil
    end
    
    data = JSON.parse(resp.body)

    if data['status'] == "404"
      return nil
    end
    props = data['properties']
    @descrip = props['textDescription']
    @temp = parseUnits(props['temperature'])
    @humidity = parseUnits(props['relativeHumidity'])
    @wind_speed = parseUnits(props['windSpeed'])
    @wind_dir = parseUnits(props['windDirection'])

    @local_time = @timezone.utc_to_local(Time.now.utc)
  end

  def parseUnits(value)
    units = value['unitCode'].split(":")[1]
    if value['value']
      return "%0.2f %s" % [value['value'], units]
    else
      return "-"
    end
  end


  #doing our best to make a valid code out of the input
  def self.iata_to_stn(code)
    if code.length == 3
      return "K" + code.upcase
    end
    return code.upcase
  end    

  def check_code
    resp = Net::HTTP.get_response(URI("https://api.weather.gov/stations"))
    if resp.code != "200"
      errors.add(:code, "couldn't be validate (API call failed)--please retry")
    else
      data = JSON.parse(resp.body)
      ids = data['features'].map {|f| f['properties']['stationIdentifier']}
      if !ids.include?(Airport.iata_to_stn(code))
        errors.add(:code, "is invalid. please enter a valid IATA airport code")
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
    
    def index
      @airports = Airport.all
      @airports.each do |ap|
        ap.load_stn
        ap.load_weather
      end
    end

    def show
    end

    def new
        @airport = Airport.new
    end
     
    def create
        @airport = Airport.new(airport_params)

        if @airport.save
          redirect_to root_url, notice: 'Airport was successfully created.'
        else
          render :new
        end
    end
      
    
    def destroy
      @airport = Airport.find(params[:id])
      @airport.destroy
      redirect_to airports_url, notice: 'Airport was successfully deleted.'
    end
    

    private
    def airport_params
      params.require(:airport).permit(:name, :code)
    end
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather.rb
require 'net/http'
require 'json'
require 'tzinfo'

class Station
  
  attr_accessor :name, :timezone, :descrip, :temp, :humidity, :wind_speed, :wind_dir, :local_time
  
  def initialize(id)
    @id = id
    load_stn
    load_weather
  end

  def load_stn
    resp = Net::HTTP.get_response(URI("https://api.weather.gov/stations/#{@id}"))
    if resp.code != "200"
      return nil
    end
    
    data = JSON.parse(resp.body)
    props = data['properties']
    @name = props['name']
    @timezone = TZInfo::Timezone.get(props['timeZone'])
  end
  
  def load_weather
    resp = Net::HTTP.get_response(URI("https://api.weather.gov/stations/#{@id}/observations/latest"))
    if resp.code != "200"
      return nil
    end
    
    data = JSON.parse(resp.body)
    props = data['properties']
    @descrip = props['textDescription']
    @temp = parseUnits(props['temperature'])
    @humidity = parseUnits(props['relativeHumidity'])
    @wind_speed = parseUnits(props['windSpeed'])
    @wind_dir = parseUnits(props['windDirection'])

    @local_time = @timezone.utc_to_local(Time.now.utc)
  end

  def parseUnits(value)
    units = value['unitCode'].split(":")[1]
    return "%0.2f %s" % [value['value'], units]
  end

  def self.is_valid?(id)
    resp = Net::HTTP.get_response(URI("https://api.weather.gov/stations"))
    puts resp
    if resp.code != "200"
      return nil
    end
    data = JSON.parse(resp.body)
    ids = data['features'].map {|f| f['properties']['stationIdentifier']}
    return ids.include?(id)
  end
end

app/views/airports/_form.html.erb
<%= form_with(model: airport, local: true) do |form| %>
<% if airport.errors.any? %>
<div id="errors">
  <ul>
    <% airport.errors.full_messages.each do |message| %>
    <li> <%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<div class="field">
  <%= form.label :code %>
  <%= form.text_field :code %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/airports/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airport Dashboard</title>
</head>

  <body>
    <h1>Airport Dashboard</h1>

    <table class="table">
      <thead>
        <tr>
          <th>Airport Name</th>
          <th>Airport Code</th>
	  <th>Local Time</th>
	  <th>Description</th>
	  <th>Temp. </th>
	  <th>Humidity</th>
	  <th>Wind Speed</th>
	  <th>Wind Direction</th>
        </tr>
      </thead>
      <tbody>
        <% @airports.each do |airport| %>
            <tr>
            <td><%= airport.name %></td>
            <td><%= airport.code %></td>
	    <td><%= airport.local_time %></td>
	    <td><%= airport.descrip %></td>
	    <td><%= airport.temp %></td>
	    <td><%= airport.humidity %></td>
	    <td><%= airport.wind_speed %></td>
	    <td><%= airport.wind_dir %></td>

	    
            <td><%= button_to "Delete", airport, method: :delete, data: {confirm: "Are you sure?" } %></td>

            </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to 'New Airport', new_airport_path %>
  </body>
</html>

app/views/airports/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>New Airport</title>
</head>

  <body>
    <h1>New Airport</h1>

    <%= render 'form', airport: @airport %>
    
    <%= link_to 'Back', root_path %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airportapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>